# Code Explanation

- 천만영화와와 비천만영화를 비교하는데 있어, 동기간 개봉되었던 영화의 관람객 수는 큰 영향을 미칠 수 있는 요소이다.
- 이를 파악하기 위한 코드이다. 코드의 흐름은 마크다운 제목들을 참고하기 바란다.

## 사용한 모듈

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from bs4 import BeautifulSoup
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from webdriver_manager.chrome import ChromeDriverManager    # 매 번 크롬 드라이버를 설치할 필요없이 자동으로
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.alert import Alert
from tqdm.notebook import tqdm
from urllib.request import urlopen
import time
import requests
import os
import glob
import shutil
import json

## 1. 영화가 상영되었던 기간의 확인을 위한 파일 불러오기

- 천만영화는 총 29개에 해당되므로, 1위~58위까지의 영화를 확인하겠다.
- 이를 위해 영화 파일들의 목록을 확인한다.

In [2]:
csv_files = glob.glob("C:\\GitTest\\10M_Movie\\movie_DB\\individual_trend\\*.csv")   # glob 모듈로 폴더 내 파일 확인

file_name = []   # 빈 리스트 생성.

for file_path in csv_files:                            # 폴더 내 파일들의 이름을 불러와 리스트에 추가
    file_name.append(os.path.basename(file_path))


file_name          # file_name 리스트의 순서가 순위 별이 아닌 ㄱ,ㄴ,ㄷ 오름차순으로 정렬되어 있음.

['1987.csv',
 '7번방의 선물.csv',
 '검사외전.csv',
 '겨울왕국 2.csv',
 '겨울왕국.csv',
 '공조.csv',
 '과속스캔들.csv',
 '관상.csv',
 '광해, 왕이 된 남자.csv',
 '괴물.csv',
 '국가대표.csv',
 '국제시장.csv',
 '극한직업.csv',
 '기생충.csv',
 '도둑들.csv',
 '디워.csv',
 '명량.csv',
 '미션임파서블-고스트프로토콜.csv',
 '밀정.csv',
 '백두산.csv',
 '범죄도시2.csv',
 '베를린.csv',
 '베테랑.csv',
 '변호인.csv',
 '보헤미안 랩소디.csv',
 '부산행.csv',
 '설국열차.csv',
 '수상한 그녀.csv',
 '스파이더맨- 노 웨이 홈.csv',
 '스파이더맨- 파 프롬 홈.csv',
 '스파이더맨- 홈 커밍.csv',
 '신과함께-인과 연.csv',
 '신과함께-죄와 벌.csv',
 '실미도.csv',
 '써니.csv',
 '아바타- 물의 길.csv',
 '아바타.csv',
 '아이언맨 3.csv',
 '알라딘.csv',
 '암살.csv',
 '어벤져스- 에이지 오브 울트론.csv',
 '어벤져스- 엔드게임.csv',
 '어벤져스- 인피니티 워.csv',
 '엑시트.csv',
 '왕의 남자.csv',
 '인터스텔라.csv',
 '최종병기 활.csv',
 '캡틴 아메리카- 시빌 워.csv',
 '탑건- 매버릭.csv',
 '태극기 휘날리며.csv',
 '택시운전사.csv',
 '트랜스포머 3.csv',
 '트랜스포머- 패자의 역습.csv',
 '트랜스포머.csv',
 '한산- 용의 출현.csv',
 '해운대.csv',
 '해적- 바다로 간 산적.csv',
 '히말라야.csv']

In [3]:
len(file_name)        # 58개 잘 불러져 왔음

58

# 비교군

In [4]:
# 1위부터 200위까지 영화 이름, 개봉일, 감독 정보, 장르, 관람 가능 연령, 상영 타입등의 정보가 담긴 csv파일 불러오기
movie_rank = pd.read_csv("C:\\GitTest\\10M_Movie\\movie_DB\\individual_movie\\movie_info_final.csv")

In [5]:
movie_rank1 = pd.read_csv("C:\\GitTest\\10M_Movie\\movie_DB\\individual_movie\\movie_info_final.csv")

In [6]:
# 파일의 이름을 영화 제목으로 저장했기 때문에 ':' 과 같은 특수기호가 있으면 저장이 되지 않아, ':'를 '-' 로 바꿔줬었음. 
# 하지만, movie_rank 데이터에는 영화제목이 여전히 ":"로 표시되어 있기 때문에 이를 - 로 바꿔준다.
for i in range(58):
    movie_rank.iloc[i,0]=movie_rank.iloc[i,0].replace(":", "-")

In [8]:
movie_rank.head(3)

,영화,개봉일,장르,영상등급,제작국가,스크린타입,감독,주연,누적관객수
0,명량,2014-07-30,"사극,액션",15세이상관람가,한국,"필름,2D,4D",김한민,"최민식,류승룡,조진웅",17615919
1,극한직업,2019-01-23,코미디,15세이상관람가,한국,2D,이병헌,"류승룡,이하늬,진선규,이동휘,공명",16266338
2,신과함께-죄와 벌,2017-12-20,"판타지,드라마",12세이상관람가,한국,"2D,4D",김용화,"하정우,차태현,주지훈,김향기,마동석",14414658

In [12]:
name = list(movie_rank['영화'][:58])            # 잘 바뀌어있음.
name

['명량',
 '극한직업',
 '신과함께-죄와 벌',
 '국제시장',
 '어벤져스- 엔드게임',
 '겨울왕국 2',
 '베테랑',
 '아바타',
 '도둑들',
 '7번방의 선물',
 '알라딘',
 '암살',
 '범죄도시2',
 '광해, 왕이 된 남자',
 '신과함께-인과 연',
 '택시운전사',
 '태극기 휘날리며',
 '부산행',
 '변호인',
 '해운대',
 '어벤져스- 인피니티 워',
 '실미도',
 '괴물',
 '아바타- 물의 길',
 '왕의 남자',
 '어벤져스- 에이지 오브 울트론',
 '인터스텔라',
 '기생충',
 '겨울왕국',
 '보헤미안 랩소디',
 '검사외전',
 '엑시트',
 '설국열차',
 '관상',
 '아이언맨 3',
 '캡틴 아메리카- 시빌 워',
 '해적- 바다로 간 산적',
 '수상한 그녀',
 '백두산',
 '과속스캔들',
 '탑건- 매버릭',
 '국가대표',
 '스파이더맨- 파 프롬 홈',
 '디워',
 '공조',
 '트랜스포머 3',
 '히말라야',
 '스파이더맨- 노 웨이 홈',
 '미션임파서블-고스트프로토콜',
 '밀정',
 '최종병기 활',
 '트랜스포머',
 '트랜스포머- 패자의 역습',
 '써니',
 '한산- 용의 출현',
 '스파이더맨- 홈 커밍',
 '1987',
 '베를린']

#### file_name 리스트의 순서가 순위 별이 아닌 ㄱ,ㄴ,ㄷ 오름차순으로 정렬되어 있기 때문에 pd.read_csv()를 하려면 순위로 된 리스트를 만들어 주어야 함

In [13]:
name_list = []
for i in name:
    name_list.append(i+".csv")
    
name_list                        # 리스트 내 파일명이 영화 순위별로 정렬 되었음

['명량.csv',
 '극한직업.csv',
 '신과함께-죄와 벌.csv',
 '국제시장.csv',
 '어벤져스- 엔드게임.csv',
 '겨울왕국 2.csv',
 '베테랑.csv',
 '아바타.csv',
 '도둑들.csv',
 '7번방의 선물.csv',
 '알라딘.csv',
 '암살.csv',
 '범죄도시2.csv',
 '광해, 왕이 된 남자.csv',
 '신과함께-인과 연.csv',
 '택시운전사.csv',
 '태극기 휘날리며.csv',
 '부산행.csv',
 '변호인.csv',
 '해운대.csv',
 '어벤져스- 인피니티 워.csv',
 '실미도.csv',
 '괴물.csv',
 '아바타- 물의 길.csv',
 '왕의 남자.csv',
 '어벤져스- 에이지 오브 울트론.csv',
 '인터스텔라.csv',
 '기생충.csv',
 '겨울왕국.csv',
 '보헤미안 랩소디.csv',
 '검사외전.csv',
 '엑시트.csv',
 '설국열차.csv',
 '관상.csv',
 '아이언맨 3.csv',
 '캡틴 아메리카- 시빌 워.csv',
 '해적- 바다로 간 산적.csv',
 '수상한 그녀.csv',
 '백두산.csv',
 '과속스캔들.csv',
 '탑건- 매버릭.csv',
 '국가대표.csv',
 '스파이더맨- 파 프롬 홈.csv',
 '디워.csv',
 '공조.csv',
 '트랜스포머 3.csv',
 '히말라야.csv',
 '스파이더맨- 노 웨이 홈.csv',
 '미션임파서블-고스트프로토콜.csv',
 '밀정.csv',
 '최종병기 활.csv',
 '트랜스포머.csv',
 '트랜스포머- 패자의 역습.csv',
 '써니.csv',
 '한산- 용의 출현.csv',
 '스파이더맨- 홈 커밍.csv',
 '1987.csv',
 '베를린.csv']

In [85]:
len(name_list)

58

## 58개의 파일을 열고, selenium을 이용해 영화가 상영되었던 기간 내 10위까지 불러온다.

In [66]:
driver = webdriver.Chrome("chromedriver")
driver.maximize_window()                                  # 원활환 selenium의 실행을 위해 윈도우 창의 크기를 최대화 한다.
url = ('https://www.kobis.or.kr/kobis/business/stat/boxs/findPeriodBoxOfficeList.do')
driver.get(url)

result=[]          # 결과를 담아줄 리스트
 
for i in tqdm(range(len(name_list))):
    df = pd.read_csv("C:\\GitTest\\10M_Movie\\movie_DB\\individual_trend\\{}".format(name_list[i]), index_col=0)
    
    a = df.iloc[0]["날짜"]         # 첫번째 행의 날짜(조회기간에서 조회시작 시점)
    b = df.iloc[-1]["날짜"]        # 마지막 행의 날짜(조회기간에서 조회마무리 시점)
    
    # 조회 기간 From 클릭
    period_start = driver.find_element(By.ID, "sSearchFrom")
    period_start.click()
    
    # 조회 기간 From에 이미 적혀있는 내용 지우기
    period_start = driver.find_element(By.ID, "sSearchFrom")
    period_start.clear()

    # 날짜 형식을 올바르게 입력해주세요. 오류창 -> 무시하고 Enter
    da = Alert(driver)
    da.accept()
    
    # 새로운 값을 입력
    period_start = driver.find_element(By.ID, "sSearchFrom")
    period_start.send_keys(a)                                  # 영화가 상영되었던 날짜의 시작 시점.
    period_start.send_keys(Keys.ENTER)

    #######################################################################################    
        
    # 조회 기간 TO 클릭
    period_end = driver.find_element(By.ID, "sSearchTo")
    period_end.click()
    
    # 조회 기간 TO에 이미 적혀있는 내용 지우기
    period_end = driver.find_element(By.ID, "sSearchTo")
    period_end.clear()

    # 날짜 형식을 올바르게 입력해주세요 오류창 -> 무시하기
    da = Alert(driver)
    da.accept()
    
    
    # 새로운 값을 입력
    period_end.send_keys(b)                                     # 영화가 상영되었던 날짜의 마지막 시점.
    period_end.send_keys(Keys.ENTER)          
    
    # 조회버튼 클릭
    driver.find_element(By.CLASS_NAME, "btn_blue").click()

    # 조회버튼을 클릭 했을 때, 로딩중입니다 기다리기
    search_element = WebDriverWait(driver, 10).until(
                    EC.presence_of_element_located((By.CLASS_NAME, "btn_blue")))
    
    
    
    # 조회버튼을 클릭하고, 설정된 조회 기간동안 상영되었던 영화들의 정보를 가져옴
    text = driver.find_element(By.XPATH, '/html/body/div[1]/div[2]/div[2]/div[4]/table/tbody').text
    
    
    # 내용이 \로 분리되기 때문에 split 해 준 후, 1위~ 10위까지 이름만 가져오려면, 3개씩 건너 뛰면서 가져오면 됨
    text.split("\n")[1:29:3] 
    
    
    same_period = []                                          # 임시 리스트
    
    for element in text.split("\n")[1:29:3]:
        print(element)
        if element in list(movie_rank1["Title"].loc[0:58]):   # 조회된 기간 동안 10위까지의 영화가 역대 영화 순위 58위 안에 들면
            same_period.append(element)                       # 그 영화들을 임시 리스트에 넣어준 후,
            print(same_period)
            
    result.append(same_period)                                # 결과를 담아줄 리스트에 넣어준다.

  0%|          | 0/58 [00:00<?, ?it/s]

명량
['명량']
해적: 바다로 간 산적
['명량', '해적: 바다로 간 산적']
타짜-신의 손
비긴 어게인
인투 더 스톰
루시
메이즈 러너
드래곤 길들이기 2
두근두근 내 인생
해무(海霧)
극한직업
['극한직업']
캡틴 마블
증인
사바하
알리타: 배틀 엔젤
뺑반
돈
드래곤 길들이기 3
항거:유관순 이야기
극장판 헬로카봇: 옴파로스 섬의 비밀
신과함께-죄와 벌
['신과함께-죄와 벌']
1987
['신과함께-죄와 벌', '1987']
블랙 팬서
코코
그것만이 내 세상
강철비
메이즈 러너: 데스 큐어
조선명탐정: 흡혈괴마의 비밀
쥬만지: 새로운 세계
위대한 쇼맨
국제시장
['국제시장']
킹스맨 : 시크릿 에이전트
조선명탐정 : 사라진 놉의 딸
님아, 그 강을 건너지 마오
호빗: 다섯 군대 전투
빅 히어로
기술자들
강남 1970
테이큰 3
오늘의 연애
어벤져스: 엔드게임
['어벤져스: 엔드게임']
기생충
['어벤져스: 엔드게임', '기생충']
악인전
알라딘
['어벤져스: 엔드게임', '기생충', '알라딘']
걸캅스
나의 특별한 형제
뽀로로 극장판 보물섬 대모험
명탐정 피카츄
고질라: 킹 오브 몬스터
배심원들
겨울왕국 2
['겨울왕국 2']
백두산
['겨울왕국 2', '백두산']
시동
천문: 하늘에 묻는다
닥터 두리틀
포드 V 페라리
블랙머니
쥬만지: 넥스트 레벨
미드웨이
해치지않아
베테랑
['베테랑']
사도
암살
['베테랑', '암살']
앤트맨
미션 임파서블: 로그네이션
메이즈 러너: 스코치 트라이얼
탐정 : 더 비기닝
인턴
마션
뷰티 인사이드
아바타
['아바타']
전우치
의형제
하모니
셜록 홈즈
퍼시 잭슨과 번개 도둑
이상한 나라의 앨리스
용서는 없다
평행이론
주유소 습격사건 2
도둑들
['도둑들']
광해, 왕이 된 남자
['도둑들', '광해, 왕이 된 남자']
바람과 함께 사라지다
다크 나이트 라이즈
이웃사람
아이스 에이지 4: 대륙 이동설
공모자들
테이큰 2
새미의 어드벤쳐 2
토탈 리콜
7번방의 선물
['7번방의 선물']
베를린
['7번방의 선물', '베를린']
신세계
연애의 온도
지.아이.조 2
파파로티
다이하드: 굿 데이 투 다이
웜 바디스
박수건달
런닝맨
알라딘
['알라딘']
기생충
['알라딘', '기생충']
엑시트
['알라딘', '기생충', '엑시트']
스파이더맨: 파 프롬 홈
['알라딘', '기생충', '엑시트', '스파이더맨: 파 프롬 홈']
라이온 킹
봉오동 전투
토이 스토리 4
분노의 질주: 홉스&쇼
사자
악인전
베테랑
['베테랑']
암살
['베테랑', '암살']
미션 임파서블: 로그네이션
앤트맨
인사이드 아웃
미니언즈
사도
뷰티 인사이드
메이즈 러너: 스코치 트라이얼
미쓰 와이프
범죄도시2
['범죄도시2']
탑건: 매버릭
['범죄도시2', '탑건: 매버릭']
쥬라기 월드: 도미니언
마녀(魔女) Part2. The Other One
토르: 러브 앤 썬더
헤어질 결심
브로커
외계+인 1부
미니언즈2
닥터 스트레인지: 대혼돈의 멀티버스
광해, 왕이 된 남자
['광해, 왕이 된 남자']
늑대소년
26년
내가 살인범이다
브레이킹 던 part2
007 스카이폴
테이큰 2
호빗: 뜻밖의 여정
나의 PS 파트너
레미제라블
신과함께-인과 연
['신과함께-인과 연']
공작
너의 결혼식
서치
목격자
미션 임파서블: 폴아웃
맘마미아!2
몬스터 호텔 3
극장판 헬로카봇 : 백악기 시대
상류사회
택시운전사
['택시운전사']
청년경찰
살인자의 기억법
혹성탈출: 종의 전쟁
애나벨 : 인형의 주인
군함도
킬러의 보디가드
슈퍼배드 3
브이아이피
장산범
태극기 휘날리며
['태극기 휘날리며']
어린 신부
범죄의 재구성
패션 오브 크라이스트
아라한 장풍대작전
효자동 이발사
목포는 항구다
실미도
['태극기 휘날리며', '실미도']
그녀를 믿지 마세요
맹부삼천지교
부산행
['부산행']
터널
인천상륙작전
덕혜옹주
밀정
['부산행', '밀정']
제이슨 본
마이펫의 이중생활
수어사이드 스쿼드
스타트렉 비욘드
라이트 아웃
변호인
['변호인']
겨울왕국
['변호인', '겨울왕국']
수상한 그녀
['변호인', '겨울왕국', '수상한 그녀']
용의자
남자가 사랑할 때
어바웃 타임
피끓는 청춘
호빗: 스마우그의 폐허
월터의 상상은 현실이 된다
썬더와 마법저택
해운대
['해운대']
국가대표
['해운대', '국가대표']
지.아이.조 : 전쟁의 서막
내 사랑 내 곁에
애자
불꽃처럼 나비처럼
해리 포터와 혼혈 왕자
업
차우
아이스 에이지 3: 공룡시대
어벤져스: 인피니티 워
['어벤져스: 인피니티 워']
독전
데드풀 2
쥬라기 월드: 폴른 킹덤
챔피언
레슬러
버닝
피터 래빗
트루스 오어 데어
한 솔로: 스타워즈 스토리
태극기 휘날리며
['태극기 휘날리며']
실미도
['태극기 휘날리며', '실미도']
말죽거리 잔혹사
반지의 제왕 : 왕의 귀환
목포는 항구다
라스트 사무라이
그녀를 믿지 마세요
내사랑 싸가지
어디선가 누군가에 무슨일이 생기면 틀림없이 나타난다 홍반장
동해물과 백두산이
괴물
['괴물']
우리들의 행복한 시간
각설탕
가문의 부활 - 가문의 영광3
몬스터 하우스
예의없는 것들
일본침몰
한반도
천하장사 마돈나
연애, 그 참을 수 없는 가벼움
아바타: 물의 길
['아바타: 물의 길']
더 퍼스트 슬램덩크
영웅
교섭
앤트맨과 와스프: 퀀텀매니아
오늘 밤, 세계에서 이 사랑이 사라진다 해도
장화신은 고양이: 끝내주는 모험
올빼미
유령
대외비
왕의 남자
['왕의 남자']
투사부일체
음란서생
나니아 연대기-사자,마녀 그리고 옷장
구세주
킹콩
흡혈형사 나도열
청춘만화
홀리데이
싸움의 기술
어벤져스: 에이지 오브 울트론
['어벤져스: 에이지 오브 울트론']
매드 맥스: 분노의 도로
악의 연대기
스파이
차이나타운
샌 안드레아스
간신
위험한 상견례 2
무뢰한
홈
인터스텔라
['인터스텔라']
국제시장
['인터스텔라', '국제시장']
님아, 그 강을 건너지 마오
호빗: 다섯 군대 전투
기술자들
테이큰 3
엑소더스: 신들과 왕들
마다가스카의 펭귄
퓨리
빅매치
알라딘
['알라딘']
기생충
['알라딘', '기생충']
스파이더맨: 파 프롬 홈
['알라딘', '기생충', '스파이더맨: 파 프롬 홈']
라이온 킹
토이 스토리 4
롱 리브 더 킹: 목포 영웅
존 윅 3: 파라벨룸
나랏말싸미
엑스맨: 다크 피닉스
맨 인 블랙: 인터내셔널
겨울왕국
['겨울왕국']
수상한 그녀
['겨울왕국', '수상한 그녀']
논스톱
남자가 사랑할 때
변호인
['겨울왕국', '수상한 그녀', '변호인']
피끓는 청춘
300: 제국의 부활
폼페이: 최후의 날
노아
찌라시: 위험한 소문
보헤미안 랩소디
['보헤미안 랩소디']
완벽한 타인
아쿠아맨
극한직업
['보헤미안 랩소디', '극한직업']
국가부도의 날
말모이
신비한 동물들과 그린델왈드의 범죄
내안의 그놈
마약왕
주먹왕 랄프 2: 인터넷 속으로
검사외전
['검사외전']
데드풀
귀향
주토피아
쿵푸팬더3
동주
좋아해줘
갓 오브 이집트
런던 해즈 폴른
널 기다리며
엑시트
['엑시트']
봉오동 전투
나쁜 녀석들: 더 무비
분노의 질주: 홉스&쇼
타짜: 원 아이드 잭
변신
사자
유열의 음악앨범
힘을 내요, 미스터 리
마이펫의 이중생활 2
관상
['관상']
설국열차
['관상', '설국열차']
숨바꼭질
더 테러 라이브
스파이
감기
나우 유 씨 미 : 마술사기단
컨저링
소원
엘리시움
관상
['관상']
소원
컨저링
스파이
화이: 괴물을 삼킨 아이
깡철이
그래비티
몬스터 대학교
슈퍼배드 2
섀도우 헌터스: 뼈의 도시
아이언맨 3
['아이언맨 3']
몽타주
분노의 질주: 더 맥시멈
위대한 개츠비
고령화 가족
전국노래자랑
스타트렉 다크니스
크루즈 패밀리
애프터 어스
전설의 주먹
캡틴 아메리카: 시빌 워
['캡틴 아메리카: 시빌 워']
곡성
엑스맨: 아포칼립스
탐정 홍길동: 사라진 마을
앵그리버드 더 무비
계춘할망
싱 스트리트
나의 소녀시대
아가씨
극장판 안녕 자두야
명량
['명량']
해적: 바다로 간 산적
['명량', '해적: 바다로 간 산적']
타짜-신의 손
비긴 어게인
메이즈 러너
인투 더 스톰
루시
두근두근 내 인생
해무(海霧)
제보자
겨울왕국
['겨울왕국']
수상한 그녀
['겨울왕국', '수상한 그녀']
논스톱
남자가 사랑할 때
노아
캡틴 아메리카: 윈터 솔져
피끓는 청춘
300: 제국의 부활
우아한 거짓말
폼페이: 최후의 날
백두산
['백두산']
남산의 부장들
시동
히트맨
천문: 하늘에 묻는다
닥터 두리틀
겨울왕국 2
['백두산', '겨울왕국 2']
해치지않아
미드웨이
신비아파트 극장판 하늘도깨비 대 요르문간드
과속스캔들
['과속스캔들']
쌍화점
워낭소리
적벽대전 2 : 최후의 결전
작전명 발키리
벤자민 버튼의 시간은 거꾸로 간다
지구가 멈추는 날
유감스러운 도시
벼랑 위의 포뇨
작전
탑건: 매버릭
['탑건: 매버릭']
한산: 용의 출현
['탑건: 매버릭', '한산: 용의 출현']
헌트
공조2: 인터내셔날
토르: 러브 앤 썬더
미니언즈2
비상선언
헤어질 결심
육사오(6/45)
외계+인 1부
해운대
['해운대']
국가대표
['해운대', '국가대표']
지.아이.조 : 전쟁의 서막
내 사랑 내 곁에
애자
굿모닝 프레지던트
불꽃처럼 나비처럼
업
아이스 에이지 3: 공룡시대
블랙
스파이더맨: 파 프롬 홈
['스파이더맨: 파 프롬 홈']
라이온 킹
알라딘
['스파이더맨: 파 프롬 홈', '알라딘']
엑시트
['스파이더맨: 파 프롬 홈', '알라딘', '엑시트']
사자
토이 스토리 4
나랏말싸미
마이펫의 이중생활 2
레드슈즈
기생충
['스파이더맨: 파 프롬 홈', '알라딘', '엑시트', '기생충']
디워
['디워']
화려한 휴가
만남의 광장
지금 사랑하는 사람과 살고 있습니까?
스타더스트
마이 파더
리턴
기담
다이 하드 4 : 죽어도 산다
라따뚜이
공조
['공조']
더 킹
조작된 도시
재심
모아나
23 아이덴티티
너의 이름은.
레지던트 이블: 파멸의 날
컨택트
트롤
트랜스포머 3
['트랜스포머 3']
해리포터와 죽음의 성물2
고지전
퀵
7광구
써니
['트랜스포머 3', '써니']
마당을 나온 암탉
고양이: 죽음을 보는 두 개의 눈
리오
퍼스트 어벤져
히말라야
['히말라야']
검사외전
['히말라야', '검사외전']
스타워즈: 깨어난 포스
쿵푸팬더3
내부자들: 디 오리지널
레버넌트: 죽음에서 돌아온 자
대호
몬스터 호텔 2
굿 다이노
셜록: 유령신부
스파이더맨: 노 웨이 홈
['스파이더맨: 노 웨이 홈']
해적: 도깨비 깃발
킹스맨: 퍼스트 에이전트
씽2게더
더 배트맨
킹메이커
언차티드
경관의 피
극장판 주술회전 0
특송
미션임파서블:고스트프로토콜
['미션임파서블:고스트프로토콜']
댄싱퀸
부러진 화살
셜록홈즈 : 그림자 게임
마이 웨이
장화신은 고양이
범죄와의 전쟁: 나쁜놈들 전성시대
퍼펙트 게임
오싹한 연애
잃어버린 세계를 찾아서 2: 신비의 섬
밀정
['밀정']
럭키
아수라
미스 페레그린과 이상한 아이들의 집
벤허
고산자, 대동여지도
맨 인 더 다크
매그니피센트 7
브리짓 존스의 베이비
설리: 허드슨강의 기적
최종병기 활
['최종병기 활']
도가니
혹성탈출: 진화의 시작
가문의 영광4 - 가문의 수난
블라인드
의뢰인
리얼 스틸
마당을 나온 암탉
개구쟁이 스머프
파퍼씨네 펭귄들
트랜스포머
['트랜스포머']
디워
['트랜스포머', '디워']
화려한 휴가
해리 포터와 불사조 기사단
다이 하드 4 : 죽어도 산다
라따뚜이
검은 집
해부학 교실
기담
샴
해운대
['해운대']
트랜스포머: 패자의 역습
['해운대', '트랜스포머: 패자의 역습']
해리 포터와 혼혈 왕자
국가대표
['해운대', '트랜스포머: 패자의 역습', '국가대표']
차우
거북이 달린다
킹콩을 들다
지.아이.조 : 전쟁의 서막
업
명탐정 코난 : 칠흑의 추적자
트랜스포머 3
['트랜스포머 3']
써니
['트랜스포머 3', '써니']
쿵푸팬더 2
해리포터와 죽음의 성물2
캐리비안의 해적: 낯선 조류
고지전
퀵
엑스맨: 퍼스트 클래스
7광구
소스 코드
한산: 용의 출현
['한산: 용의 출현']
공조2: 인터내셔날
헌트
비상선언
육사오(6/45)
탑건: 매버릭
['한산: 용의 출현', '탑건: 매버릭']
미니언즈2
외계+인 1부
뽀로로 극장판 드래곤캐슬 대모험
놉
스파이더맨: 홈 커밍
['스파이더맨: 홈 커밍']
군함도
택시운전사
['스파이더맨: 홈 커밍', '택시운전사']
슈퍼배드 3
덩케르크
박열
47 미터
카3: 새로운 도전
명탐정 코난:진홍의 연가
플립
신과함께-죄와 벌
['신과함께-죄와 벌']
1987
['신과함께-죄와 벌', '1987']
코코
그것만이 내 세상
메이즈 러너: 데스 큐어
쥬만지: 새로운 세계
조선명탐정: 흡혈괴마의 비밀
염력
강철비
위대한 쇼맨
7번방의 선물
['7번방의 선물']
베를린
['7번방의 선물', '베를린']
신세계
다이하드: 굿 데이 투 다이
파파로티
웜 바디스
잭 더 자이언트 킬러
연애의 온도
남쪽으로 튀어
사이코메트리

## 결과

In [86]:
result                          # ex) 명량이 상영되었던 동기간에 상영된 영화들 중 58위 안에 있는 영화들

[['명량', '해적: 바다로 간 산적'],
 ['극한직업'],
 ['신과함께-죄와 벌', '1987'],
 ['국제시장'],
 ['어벤져스: 엔드게임', '기생충', '알라딘'],
 ['겨울왕국 2', '백두산'],
 ['베테랑', '암살'],
 ['아바타'],
 ['도둑들', '광해, 왕이 된 남자'],
 ['7번방의 선물', '베를린'],
 ['알라딘', '기생충', '엑시트', '스파이더맨: 파 프롬 홈'],
 ['베테랑', '암살'],
 ['범죄도시2', '탑건: 매버릭'],
 ['광해, 왕이 된 남자'],
 ['신과함께-인과 연'],
 ['택시운전사'],
 ['태극기 휘날리며', '실미도'],
 ['부산행', '밀정'],
 ['변호인', '겨울왕국', '수상한 그녀'],
 ['해운대', '국가대표'],
 ['어벤져스: 인피니티 워'],
 ['태극기 휘날리며', '실미도'],
 ['괴물'],
 ['아바타: 물의 길'],
 ['왕의 남자'],
 ['어벤져스: 에이지 오브 울트론'],
 ['인터스텔라', '국제시장'],
 ['알라딘', '기생충', '스파이더맨: 파 프롬 홈'],
 ['겨울왕국', '수상한 그녀', '변호인'],
 ['보헤미안 랩소디', '극한직업'],
 ['검사외전'],
 ['엑시트'],
 ['관상', '설국열차'],
 ['관상'],
 ['아이언맨 3'],
 ['캡틴 아메리카: 시빌 워'],
 ['명량', '해적: 바다로 간 산적'],
 ['겨울왕국', '수상한 그녀'],
 ['백두산', '겨울왕국 2'],
 ['과속스캔들'],
 ['탑건: 매버릭', '한산: 용의 출현'],
 ['해운대', '국가대표'],
 ['스파이더맨: 파 프롬 홈', '알라딘', '엑시트', '기생충'],
 ['디워'],
 ['공조'],
 ['트랜스포머 3', '써니'],
 ['히말라야', '검사외전'],
 ['스파이더맨: 노 웨이 홈'],
 ['미션임파서블:고스트프로토콜'],
 ['밀정'],
 ['최종병기 활'],
 ['트랜스포머', '디워'],
 ['해운대', '트랜스포머: 패자의 역습', '국가대표'],
 ['트랜스포머 3', '써니'],
 ['한산: 용의 출현', '탑건: 매버릭'],
 ['스파이더맨: 홈 커밍', '택시운전사'],
 ['신과함께-죄와 벌', '1987'],
 ['7번방의 선물', '베를린']]

In [90]:
name = list(movie_rank1['Title'][:58])                            
name                                     # 1위부터 58위까지의 영화 제목 리스트

['명량',
 '극한직업',
 '신과함께-죄와 벌',
 '국제시장',
 '어벤져스: 엔드게임',
 '겨울왕국 2',
 '베테랑',
 '아바타',
 '도둑들',
 '7번방의 선물',
 '알라딘',
 '암살',
 '범죄도시2',
 '광해, 왕이 된 남자',
 '신과함께-인과 연',
 '택시운전사',
 '태극기 휘날리며',
 '부산행',
 '변호인',
 '해운대',
 '어벤져스: 인피니티 워',
 '실미도',
 '괴물',
 '아바타: 물의 길',
 '왕의 남자',
 '어벤져스: 에이지 오브 울트론',
 '인터스텔라',
 '기생충',
 '겨울왕국',
 '보헤미안 랩소디',
 '검사외전',
 '엑시트',
 '설국열차',
 '관상',
 '아이언맨 3',
 '캡틴 아메리카: 시빌 워',
 '해적: 바다로 간 산적',
 '수상한 그녀',
 '백두산',
 '과속스캔들',
 '탑건: 매버릭',
 '국가대표',
 '스파이더맨: 파 프롬 홈',
 '디워',
 '공조',
 '트랜스포머 3',
 '히말라야',
 '스파이더맨: 노 웨이 홈',
 '미션임파서블:고스트프로토콜',
 '밀정',
 '최종병기 활',
 '트랜스포머',
 '트랜스포머: 패자의 역습',
 '써니',
 '한산: 용의 출현',
 '스파이더맨: 홈 커밍',
 '1987',
 '베를린']

In [91]:
same_period_info = dict(zip(name, result))             # 이들을 dict로 매핑 시켜준다.

#### 결과 dict

- ex) 명량이 상영되었을 당시 해적: 바다로 간 산적은 아쉽게 천만 영화를 달성하지 못함.

In [92]:
same_period_info

{'명량': ['명량', '해적: 바다로 간 산적'],
 '극한직업': ['극한직업'],
 '신과함께-죄와 벌': ['신과함께-죄와 벌', '1987'],
 '국제시장': ['국제시장'],
 '어벤져스: 엔드게임': ['어벤져스: 엔드게임', '기생충', '알라딘'],
 '겨울왕국 2': ['겨울왕국 2', '백두산'],
 '베테랑': ['베테랑', '암살'],
 '아바타': ['아바타'],
 '도둑들': ['도둑들', '광해, 왕이 된 남자'],
 '7번방의 선물': ['7번방의 선물', '베를린'],
 '알라딘': ['알라딘', '기생충', '엑시트', '스파이더맨: 파 프롬 홈'],
 '암살': ['베테랑', '암살'],
 '범죄도시2': ['범죄도시2', '탑건: 매버릭'],
 '광해, 왕이 된 남자': ['광해, 왕이 된 남자'],
 '신과함께-인과 연': ['신과함께-인과 연'],
 '택시운전사': ['택시운전사'],
 '태극기 휘날리며': ['태극기 휘날리며', '실미도'],
 '부산행': ['부산행', '밀정'],
 '변호인': ['변호인', '겨울왕국', '수상한 그녀'],
 '해운대': ['해운대', '국가대표'],
 '어벤져스: 인피니티 워': ['어벤져스: 인피니티 워'],
 '실미도': ['태극기 휘날리며', '실미도'],
 '괴물': ['괴물'],
 '아바타: 물의 길': ['아바타: 물의 길'],
 '왕의 남자': ['왕의 남자'],
 '어벤져스: 에이지 오브 울트론': ['어벤져스: 에이지 오브 울트론'],
 '인터스텔라': ['인터스텔라', '국제시장'],
 '기생충': ['알라딘', '기생충', '스파이더맨: 파 프롬 홈'],
 '겨울왕국': ['겨울왕국', '수상한 그녀', '변호인'],
 '보헤미안 랩소디': ['보헤미안 랩소디', '극한직업'],
 '검사외전': ['검사외전'],
 '엑시트': ['엑시트'],
 '설국열차': ['관상', '설국열차'],
 '관상': ['관상'],
 '아이언맨 3': ['아이언맨 3'],
 '캡틴 아메리카: 시빌 워': ['캡틴 아메리카: 시빌 워'],
 '해적: 바다로 간 산적': ['명량', '해적: 바다로 간 산적'],
 '수상한 그녀': ['겨울왕국', '수상한 그녀'],
 '백두산': ['백두산', '겨울왕국 2'],
 '과속스캔들': ['과속스캔들'],
 '탑건: 매버릭': ['탑건: 매버릭', '한산: 용의 출현'],
 '국가대표': ['해운대', '국가대표'],
 '스파이더맨: 파 프롬 홈': ['스파이더맨: 파 프롬 홈', '알라딘', '엑시트', '기생충'],
 '디워': ['디워'],
 '공조': ['공조'],
 '트랜스포머 3': ['트랜스포머 3', '써니'],
 '히말라야': ['히말라야', '검사외전'],
 '스파이더맨: 노 웨이 홈': ['스파이더맨: 노 웨이 홈'],
 '미션임파서블:고스트프로토콜': ['미션임파서블:고스트프로토콜'],
 '밀정': ['밀정'],
 '최종병기 활': ['최종병기 활'],
 '트랜스포머': ['트랜스포머', '디워'],
 '트랜스포머: 패자의 역습': ['해운대', '트랜스포머: 패자의 역습', '국가대표'],
 '써니': ['트랜스포머 3', '써니'],
 '한산: 용의 출현': ['한산: 용의 출현', '탑건: 매버릭'],
 '스파이더맨: 홈 커밍': ['스파이더맨: 홈 커밍', '택시운전사'],
 '1987': ['신과함께-죄와 벌', '1987'],
 '베를린': ['7번방의 선물', '베를린']}

## 결과 저장 -> json형식

In [98]:
# 딕셔너리 데이터를 JSON 문자열로 변환
my_json = json.dumps(same_period_info)

# JSON 문자열을 파일로 저장
with open('same_period_info.json', 'w') as f:
    f.write(my_json)

## 결과를 dict형으로 다시 불러오고 싶다면?

In [99]:
# JSON 파일을 읽어서 문자열로 저장
with open('same_period_info.json', 'r') as f:
    my_json = f.read()

# JSON 문자열을 딕셔너리로 변환
same_period_info1 = json.loads(my_json)

In [101]:
same_period_info1

{'명량': ['명량', '해적: 바다로 간 산적'],
 '극한직업': ['극한직업'],
 '신과함께-죄와 벌': ['신과함께-죄와 벌', '1987'],
 '국제시장': ['국제시장'],
 '어벤져스: 엔드게임': ['어벤져스: 엔드게임', '기생충', '알라딘'],
 '겨울왕국 2': ['겨울왕국 2', '백두산'],
 '베테랑': ['베테랑', '암살'],
 '아바타': ['아바타'],
 '도둑들': ['도둑들', '광해, 왕이 된 남자'],
 '7번방의 선물': ['7번방의 선물', '베를린'],
 '알라딘': ['알라딘', '기생충', '엑시트', '스파이더맨: 파 프롬 홈'],
 '암살': ['베테랑', '암살'],
 '범죄도시2': ['범죄도시2', '탑건: 매버릭'],
 '광해, 왕이 된 남자': ['광해, 왕이 된 남자'],
 '신과함께-인과 연': ['신과함께-인과 연'],
 '택시운전사': ['택시운전사'],
 '태극기 휘날리며': ['태극기 휘날리며', '실미도'],
 '부산행': ['부산행', '밀정'],
 '변호인': ['변호인', '겨울왕국', '수상한 그녀'],
 '해운대': ['해운대', '국가대표'],
 '어벤져스: 인피니티 워': ['어벤져스: 인피니티 워'],
 '실미도': ['태극기 휘날리며', '실미도'],
 '괴물': ['괴물'],
 '아바타: 물의 길': ['아바타: 물의 길'],
 '왕의 남자': ['왕의 남자'],
 '어벤져스: 에이지 오브 울트론': ['어벤져스: 에이지 오브 울트론'],
 '인터스텔라': ['인터스텔라', '국제시장'],
 '기생충': ['알라딘', '기생충', '스파이더맨: 파 프롬 홈'],
 '겨울왕국': ['겨울왕국', '수상한 그녀', '변호인'],
 '보헤미안 랩소디': ['보헤미안 랩소디', '극한직업'],
 '검사외전': ['검사외전'],
 '엑시트': ['엑시트'],
 '설국열차': ['관상', '설국열차'],
 '관상': ['관상'],
 '아이언맨 3': ['아이언맨 3'],
 '캡틴 아메리카: 시빌 워': ['캡틴 아메리카: 시빌 워'],
 '해적: 바다로 간 산적': ['명량', '해적: 바다로 간 산적'],
 '수상한 그녀': ['겨울왕국', '수상한 그녀'],
 '백두산': ['백두산', '겨울왕국 2'],
 '과속스캔들': ['과속스캔들'],
 '탑건: 매버릭': ['탑건: 매버릭', '한산: 용의 출현'],
 '국가대표': ['해운대', '국가대표'],
 '스파이더맨: 파 프롬 홈': ['스파이더맨: 파 프롬 홈', '알라딘', '엑시트', '기생충'],
 '디워': ['디워'],
 '공조': ['공조'],
 '트랜스포머 3': ['트랜스포머 3', '써니'],
 '히말라야': ['히말라야', '검사외전'],
 '스파이더맨: 노 웨이 홈': ['스파이더맨: 노 웨이 홈'],
 '미션임파서블:고스트프로토콜': ['미션임파서블:고스트프로토콜'],
 '밀정': ['밀정'],
 '최종병기 활': ['최종병기 활'],
 '트랜스포머': ['트랜스포머', '디워'],
 '트랜스포머: 패자의 역습': ['해운대', '트랜스포머: 패자의 역습', '국가대표'],
 '써니': ['트랜스포머 3', '써니'],
 '한산: 용의 출현': ['한산: 용의 출현', '탑건: 매버릭'],
 '스파이더맨: 홈 커밍': ['스파이더맨: 홈 커밍', '택시운전사'],
 '1987': ['신과함께-죄와 벌', '1987'],
 '베를린': ['7번방의 선물', '베를린']}

In [102]:
type(same_period_info1)  # type 확인 : dict

dict

In [22]:
name_list[0]

'명량.csv'

In [31]:
for i in tqdm(range(len(name_list))):
    df = pd.read_csv("C:\\GitTest\\10M_Movie\\movie_DB\\individual_trend\\{}".format(name_list[i]), index_col=0)
    
    me = pd.merge(df, price1, how='left')
    
    me.to_csv("C:\\GitTest\\Moviewithprice\\{}".format(name_list[i]), index=False)

  0%|          | 0/58 [00:00<?, ?it/s]

In [25]:
df = pd.read_csv("C:\\GitTest\\10M_Movie\\movie_DB\\individual_trend\\명량.csv",index_col=0)

In [29]:
me = pd.merge(df, price1, how='left')

In [30]:
me

,날짜,스크린수,스크린점유율,상영횟수,상영점유율,좌석수,좌석점유율,좌석판매율,매출액,매출액증감(전일대비),관객수,관객수증감(전일대비),누적매출액,누적관객수,순위,가격
0,2014-07-30,1159,0.336,6147,0.423,1152173,0.484,0.593,4708879000,4649246000,682701,674628,4881110000,705201,1,9000
1,2014-07-31,1202,0.318,6258,0.421,1176034,0.483,0.600,5243409900,534530900,705070,22369,10124519900,1410271,1,9000
2,2014-08-01,1300,0.337,6699,0.444,1255037,0.509,0.691,6918410307,1675000407,867437,162367,17042930207,2277708,1,10000
3,2014-08-02,1494,0.376,7605,0.491,1402659,0.553,0.879,9826541209,2908130902,1232529,365092,26869471416,3510237,1,10000
4,2014-08-03,1587,0.398,7963,0.521,1456645,0.582,0.863,10031212500,204671291,1257380,24851,36900683916,4767617,1,10000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,2014-09-27,110,0.023,218,0.014,26383,0.010,0.177,37704900,20115500,4676,2420,135599116610,17592610,14,10000
60,2014-09-28,108,0.023,213,0.014,25973,0.011,0.204,42873600,5168700,5304,628,135641990210,17597914,11,10000
61,2014-09-29,112,0.026,206,0.015,25616,0.011,0.090,16794400,-26079200,2312,-2992,135658784610,17600226,14,9000
62,2014-09-30,107,0.025,204,0.015,25397,0.011,0.083,15225700,-1568700,2102,-210,135674010310,17602328,13,9000
63,2014-10-01,111,0.025,205,0.015,25759,0.011,0.086,15733600,507900,2216,114,135689743910,17604544,13,9000

In [17]:
price = pd.read_csv('C:\\GitTest\\10M_Movie\\movie_DB\\macro_envirment\\daily_macro.csv')

In [18]:
price

,날짜,전체개봉편수,전체상영편수,전체매출액,전체관객수,요일,가격,공휴일,평균기온,최저기온,최고기온,강수량
0,2004-01-01,1,7,727005000,113837,Thu,7000,1,3.7,1.2,5.9,0.0
1,2004-01-02,0,7,642276500,104357,Fri,7000,0,3.1,1.6,5.5,3.0
2,2004-01-03,0,7,796519500,125234,Sat,7000,0,3.9,1.6,7.1,0.0
3,2004-01-04,0,7,763271000,120203,Sun,7000,0,1.8,-1.7,6.8,0.0
4,2004-01-05,0,7,409269500,64180,Mon,7000,0,2.9,-2.2,8.1,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
7031,2023-04-02,0,80,3423512979,336191,Sun,14000,0,18.8,11.9,25.2,0.0
7032,2023-04-03,0,87,802358725,81632,Mon,13000,0,19.0,11.3,25.9,0.0
7033,2023-04-04,2,91,815279367,82221,Tue,13000,0,17.6,12.7,21.7,6.9
7034,2023-04-05,6,94,1347838240,134732,Wed,13000,0,11.9,8.7,14.9,50.3
7035,2023-04-06,7,100,1058649412,107135,Thu,13000,0,8.8,7.4,9.7,2.7

In [20]:
price1 = price[["날짜","가격"]]

In [21]:
price1

              날짜     가격
0     2004-01-01   7000
1     2004-01-02   7000
2     2004-01-03   7000
3     2004-01-04   7000
4     2004-01-05   7000
...          ...    ...
7031  2023-04-02  14000
7032  2023-04-03  13000
7033  2023-04-04  13000
7034  2023-04-05  13000
7035  2023-04-06  13000

[7036 rows x 2 columns]